var files_dup =
[
    [ "bit2vec.h", "db/d3a/bit2vec_8h.html", "db/d3a/bit2vec_8h" ],
    [ "bitsvec.h", "d8/d95/bitsvec_8h.html", "d8/d95/bitsvec_8h" ],
    [ "bitvec.h", "d5/d34/bitvec_8h.html", "d5/d34/bitvec_8h" ],
    [ "chararray.h", "d0/d2a/chararray_8h.html", "d0/d2a/chararray_8h" ],
    [ "dagcns.h", "d0/d48/dagcns_8h.html", "d0/d48/dagcns_8h" ],
    [ "dbgcns.h", "d3/d39/dbgcns_8h.html", "d3/d39/dbgcns_8h" ],
    [ "dna.h", "d0/df5/dna_8h.html", "d0/df5/dna_8h" ],
    [ "filereader.h", "de/dc8/filereader_8h.html", "de/dc8/filereader_8h" ],
    [ "filewriter.h", "d4/d62/filewriter_8h.html", "d4/d62/filewriter_8h" ],
    [ "general_graph.h", "d4/deb/general__graph_8h.html", "d4/deb/general__graph_8h" ],
    [ "hashset.h", "d1/dcf/hashset_8h.html", "d1/dcf/hashset_8h" ],
    [ "kbm.c", "d4/d4d/kbm_8c.html", "d4/d4d/kbm_8c" ],
    [ "kbm.h", "d3/d62/kbm_8h.html", "d3/d62/kbm_8h" ],
    [ "kbmpoa.h", "d8/d2a/kbmpoa_8h.html", "d8/d2a/kbmpoa_8h" ],
    [ "ksw.c", "d6/d1c/ksw_8c.html", "d6/d1c/ksw_8c" ],
    [ "ksw.h", "d5/d97/ksw_8h.html", "d5/d97/ksw_8h" ],
    [ "kswx.h", "d2/df4/kswx_8h.html", "d2/df4/kswx_8h" ],
    [ "list.h", "da/d23/list_8h.html", "da/d23/list_8h" ],
    [ "mem_share.h", "d5/d11/mem__share_8h.html", "d5/d11/mem__share_8h" ],
    [ "pgzf.c", "d0/d18/pgzf_8c.html", "d0/d18/pgzf_8c" ],
    [ "pgzf.h", "d0/df1/pgzf_8h.html", "d0/df1/pgzf_8h" ],
    [ "poacns.h", "df/da2/poacns_8h.html", "df/da2/poacns_8h" ],
    [ "queue.h", "d8/d38/queue_8h.html", "d8/d38/queue_8h" ],
    [ "sort.h", "d7/d50/sort_8h.html", "d7/d50/sort_8h" ],
    [ "thread.h", "db/dd5/thread_8h.html", "db/dd5/thread_8h" ],
    [ "tripoa.h", "d1/dd3/tripoa_8h.html", "d1/dd3/tripoa_8h" ],
    [ "txtplot.h", "dc/d87/txtplot_8h.html", "dc/d87/txtplot_8h" ],
    [ "wtdbg-cns.c", "d3/d03/wtdbg-cns_8c.html", "d3/d03/wtdbg-cns_8c" ],
    [ "wtdbg-graph.h", "d4/d4d/wtdbg-graph_8h.html", "d4/d4d/wtdbg-graph_8h" ],
    [ "wtdbg.c", "db/d54/wtdbg_8c.html", "db/d54/wtdbg_8c" ],
    [ "wtdbg.h", "de/d6d/wtdbg_8h.html", "de/d6d/wtdbg_8h" ],
    [ "wtpoa-cns.c", "d0/dcc/wtpoa-cns_8c.html", "d0/dcc/wtpoa-cns_8c" ],
    [ "wtpoa.h", "db/d1f/wtpoa_8h.html", "db/d1f/wtpoa_8h" ]
];